apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: otel-agent
  namespace: monitoring
spec:
  mode: daemonset
  serviceAccount: otel-collector
  hostNetwork: true
  image: ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-contrib:0.160.0@sha256:799dc6cf12c96192af37b5bdba804da8c10b3bc563b43cb90c3f3c58d9572ad6

  env:
    - name: K8S_NODE_NAME
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName

  config:
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318

      kubeletstats:
        collection_interval: 20s
        endpoint: "https://${env:K8S_NODE_NAME}:10250"
        insecure_skip_verify: true
        auth_type: "serviceAccount"

      hostmetrics:
        collection_interval: 20s
        root_path: /hostfs
        scrapers:
          cpu: {}
          memory: {}
          disk: {}
          filesystem:
            exclude_mount_points:
              match_type: regexp
              mount_points:
                - ^/(dev|proc|sys|var/lib/docker|var/lib/kubelet).*
            exclude_fs_types:
              match_type: regexp
              fs_types:
                - ^(autofs|binfmt_misc|bpf|cgroup2|configfs|debugfs|devpts|devtmpfs|fusectl|hugetlbfs|iso9660|mqueue|nsfs|overlay|proc|pstore|securityfs|selinuxfs|squashfs|sysfs|tracefs)$
          network: {}
          load: {}

    processors:
      memory_limiter:
        check_interval: 1s
        limit_percentage: 75
        spike_limit_percentage: 15

      k8sattributes:
        filter:
          node_from_env_var: K8S_NODE_NAME
        passthrough: false
        extract:
          metadata:
            - k8s.pod.name
            - k8s.pod.uid
            - k8s.namespace.name
            - k8s.deployment.name
            - k8s.statefulset.name
            - k8s.daemonset.name
            - k8s.cronjob.name
            - k8s.job.name
            - k8s.node.name

      resource:
        attributes:
          - key: cluster.name
            value: "talos-homelab"
            action: upsert

      batch:
        send_batch_size: 1000
        timeout: 10s

    exporters:
      otlp/gateway:
        endpoint: "otel-gateway-collector:4317"
        tls:
          insecure: true

    service:
      pipelines:
        metrics:
          receivers: [otlp, kubeletstats, hostmetrics]
          processors: [memory_limiter, k8sattributes, resource, batch]
          exporters: [otlp/gateway]

  volumeMounts:
    - name: hostfs
      mountPath: /hostfs
      readOnly: true
    - name: varlogpods
      mountPath: /var/log/pods
      readOnly: true

  volumes:
    - name: hostfs
      hostPath:
        path: /
    - name: varlogpods
      hostPath:
        path: /var/log/pods

  resources:
    limits:
      cpu: 256m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 128Mi
